# Generated by Django 4.2.24 on 2025-09-16 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='income',
        ),
        migrations.AddField(
            model_name='sale',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('FF', 'Fast Food'), ('IT', 'Italian'), ('EG', 'Egyption'), ('DR', 'Drinks'), ('AR', 'Arabian'), ('OT', 'Other')], max_length=2),
        ),
    ]
